"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1500

format = """
$character\
$directory\
$git_branch\
${custom.git_dirty}\
$git_status"""

add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
style = "bold cyan"
truncation_length = 1
truncate_to_repo = false
read_only = ' 🔒'

[git_branch]
format = '[git:\(](bold blue)[$branch](bold red)[\)](bold blue) '

[git_status]
format = '([$ahead_behind]($style) )'
ahead = '⇡'
behind = '⇣'
diverged = '⇡⇣'
style = 'bold yellow'
use_git_executable = true

[custom.git_dirty]
shell = ['sh']
when = 'test -n "$(git status --porcelain --ignore-submodules 2>/dev/null)"'
require_repo = true
symbol = '✗'
style = 'bold yellow'
format = '[$symbol]($style) '
